Repository massgov/mayflower, pull requests merged in 2018-03, with the labels that each got.

#723 fix 'our organizations' and 'mosaic' layouts on IE11
  styleguide/source/assets/scss/03-organisms/_featured-item-mosaic.scss
  styleguide/source/assets/scss/03-organisms/_image-link-list.scss
Labels: browser bug, patch, quick-fix

#729 DP-8190 iframes are showing a blue shading
  changelogs/DP-8190.txt
  styleguide/source/assets/scss/06-theme/01-atoms/_iframe.scss
Labels: css, minor

#724 DP-8203 Mayflower display issues
  changelogs/DP-8203.txt
  styleguide/source/_patterns/02-molecules/contact-us.twig
  styleguide/source/assets/scss/03-organisms/_header-alert.scss
Labels: minor

#732 DP-6883: Use a function to embed SVG icons for download link
  changelogs/DP-6883.txt
  styleguide/source/_patterns/01-atoms/05-icons/svg-doc-generic.twig
  styleguide/source/_patterns/02-molecules/download-link.twig
  styleguide/source/_patterns/03-organisms/by-author/form-downloads.json
  styleguide/source/_patterns/03-organisms/by-author/form-downloads~as-listing.json
  styleguide/source/_patterns/04-templates/01-content-types/binder-page.json
  styleguide/source/_patterns/04-templates/01-content-types/court-rules.json
  styleguide/source/_patterns/04-templates/01-content-types/event.json
  styleguide/source/_patterns/04-templates/01-content-types/policy-advisory.json
  styleguide/source/_patterns/04-templates/01-content-types/services.json
  styleguide/source/_patterns/05-pages/G2G/G2G-Service-Unemployment-Benefits.json
  styleguide/source/_patterns/05-pages/board-decision.json
  styleguide/source/_patterns/05-pages/detail-for-service-howto-location.json
  styleguide/source/_patterns/05-pages/event~public-meeting-agenda.json
  styleguide/source/_patterns/05-pages/event~public-meeting-minutes.json
  styleguide/source/_patterns/05-pages/event~public-meeting.json
  styleguide/source/_patterns/05-pages/event~recurring.json
  styleguide/source/_patterns/05-pages/executive-order.json
  styleguide/source/_patterns/05-pages/guide-section-all-fields.json
  styleguide/source/_patterns/05-pages/guide.json
  styleguide/source/_patterns/05-pages/howto.json
  styleguide/source/_patterns/05-pages/information-details.json
  styleguide/source/_patterns/05-pages/listing-links.json
  styleguide/source/_patterns/05-pages/location-general-content.json
  styleguide/source/_patterns/05-pages/policy-advisory-directive.json
  styleguide/source/_patterns/05-pages/regulation.json
  styleguide/source/_patterns/05-pages/rules-of-court.json
  styleguide/source/_patterns/05-pages/service.json
  styleguide/source/_twig-components/functions/icon.function.php
  styleguide/source/assets/images/svg-icons/doc-generic.svg
  styleguide/source/assets/js/vendor/bower.json
  styleguide/source/assets/js/vendor/bower_components/polyfill-init/index.js
  styleguide/source/assets/js/vendor/bower_components/svg4everybody/.bower.json
  styleguide/source/assets/js/vendor/bower_components/svg4everybody/CHANGELOG.md
  styleguide/source/assets/js/vendor/bower_components/svg4everybody/Gruntfile.js
  styleguide/source/assets/js/vendor/bower_components/svg4everybody/README.md
  styleguide/source/assets/js/vendor/bower_components/svg4everybody/bower.json
  styleguide/source/assets/js/vendor/bower_components/svg4everybody/dist/svg4everybody.js
  styleguide/source/assets/js/vendor/bower_components/svg4everybody/dist/svg4everybody.legacy.js
  styleguide/source/assets/js/vendor/bower_components/svg4everybody/dist/svg4everybody.legacy.min.js
  styleguide/source/assets/js/vendor/bower_components/svg4everybody/dist/svg4everybody.min.js
  styleguide/source/assets/js/vendor/bower_components/svg4everybody/lib/svg4everybody.js
  styleguide/source/assets/js/vendor/bower_components/svg4everybody/package.json
  styleguide/source/assets/js/vendor/bower_components/svg4everybody/test/1138.png
  styleguide/source/assets/js/vendor/bower_components/svg4everybody/test/demo.svg
  styleguide/source/assets/js/vendor/bower_components/svg4everybody/test/demo.svg.1138.png
  styleguide/source/assets/js/vendor/bower_components/svg4everybody/test/demo.svg.camera.png
  styleguide/source/assets/js/vendor/bower_components/svg4everybody/test/demo.svg.eye.png
  styleguide/source/assets/js/vendor/bower_components/svg4everybody/test/demo.svg.pencil.png
  styleguide/source/assets/js/vendor/bower_components/svg4everybody/test/eye.png
  styleguide/source/assets/js/vendor/bower_components/svg4everybody/test/index.html
  styleguide/source/assets/js/vendor/polyfill-init.js
Labels: enhancement, major

#710 DP 7767 binder page navigation
  styleguide/source/_patterns/03-organisms/by-author/page-flipper.md
  styleguide/source/_patterns/03-organisms/by-author/page-flipper.twig
  styleguide/source/_patterns/03-organisms/by-author/page-flipper~with-context.json
  styleguide/source/_patterns/03-organisms/by-template/table-of-contents-hierarchy.json
  styleguide/source/_patterns/03-organisms/by-template/table-of-contents-hierarchy.md
  styleguide/source/_patterns/03-organisms/by-template/table-of-contents-hierarchy.twig
  styleguide/source/_patterns/03-organisms/by-template/table-of-contents-overlay.json
  styleguide/source/_patterns/03-organisms/by-template/table-of-contents-overlay.md
  styleguide/source/_patterns/03-organisms/by-template/table-of-contents-overlay.twig
  styleguide/source/_patterns/04-templates/01-content-types/binder-page.json
  styleguide/source/_patterns/04-templates/01-content-types/binder-page.twig
  styleguide/source/_patterns/05-pages/binder-page-internal.json
  styleguide/source/_patterns/05-pages/binder-page-internal.md
  styleguide/source/_patterns/05-pages/binder-page-internal.twig
  styleguide/source/assets/js/helpers/throttle.js
  styleguide/source/assets/js/index.js
  styleguide/source/assets/js/modules/inlineOverlay.js
  styleguide/source/assets/scss/01-atoms/global/_elements.scss
  styleguide/source/assets/scss/03-organisms/_page-flipper.scss
  styleguide/source/assets/scss/03-organisms/_table-of-contents-hierarchy.scss
  styleguide/source/assets/scss/03-organisms/_table-of-contents-overlay.scss
  styleguide/source/assets/scss/04-templates/_binder-page.scss
  styleguide/source/assets/scss/06-theme/03-organisms/_page-flipper.scss
  styleguide/source/assets/scss/06-theme/03-organisms/_table-of-contents--hierarchy.scss
  styleguide/source/assets/scss/06-theme/03-organisms/_table-of-contents--overlay.scss
  styleguide/source/assets/scss/base-theme.scss
  styleguide/source/assets/scss/index.scss
Labels: feature, minor
