Repository massgov/mayflower, pull requests merged in 2018-09, with the labels that each got.

#244 DP-8086: Mayflower React: Port General Teaser Molecule from Mass.Gov Search.
  changelogs/DP-8086.txt
  react/.storybook/config.js
  react/backstop/backstop.js
  react/backstop/data/bitmaps_reference/vrt_molecules_CalloutLink_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/vrt_molecules_CalloutLink_0_document_1_tablet.png
  react/backstop/data/bitmaps_reference/vrt_molecules_CalloutLink_with_Description_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/vrt_molecules_CalloutLink_with_Description_0_document_1_tablet.png
  react/backstop/data/bitmaps_reference/vrt_molecules_CalloutLink_with_Details_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/vrt_molecules_CalloutLink_with_Details_0_document_1_tablet.png
  react/backstop/data/bitmaps_reference/vrt_molecules_IconLink_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/vrt_molecules_IconLink_0_document_1_tablet.png
  react/backstop/data/bitmaps_reference/vrt_molecules_IconLink_IconLink_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/vrt_molecules_IconLink_IconLink_0_document_1_tablet.png
  react/backstop/data/bitmaps_reference/vrt_molecules_ImagePromo_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/vrt_molecules_ImagePromo_0_document_1_tablet.png
  react/backstop/data/bitmaps_reference/vrt_molecules_ImagePromo_as_orgInfo_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/vrt_molecules_ImagePromo_as_orgInfo_0_document_1_tablet.png
  react/backstop/data/bitmaps_reference/vrt_molecules_ImagePromo_with_map_link_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/vrt_molecules_ImagePromo_with_map_link_0_document_1_tablet.png
  react/backstop/data/bitmaps_reference/vrt_molecules_Link_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/vrt_molecules_Link_0_document_1_tablet.png
  react/backstop/data/bitmaps_reference/vrt_organisms_Footer_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/vrt_organisms_Footer_0_document_1_tablet.png
  react/backstop/data/bitmaps_reference/vrt_organisms_Footer_with_live_JSON_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/vrt_organisms_Footer_with_live_JSON_0_document_1_tablet.png
  react/backstop/data/bitmaps_reference/vrt_organisms_GeneralTeaser_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/vrt_organisms_GeneralTeaser_0_document_1_tablet.png
  react/backstop/storyBookBackstop.js
  react/src/components/atoms/icons/Icon/Icon.knob.options.js
  react/src/components/atoms/icons/Icon/Icon.stories.js
  react/src/components/atoms/icons/Icon/index.js
  react/src/components/atoms/media/Image/Image.stories.js
  react/src/components/atoms/media/Image/index.js
  react/src/components/molecules/IconLink/IconLink.stories.js
  react/src/components/molecules/IconLink/index.js
  react/src/components/molecules/Link/Link.knob.options.js
  react/src/components/molecules/Link/Link.md
  react/src/components/molecules/Link/Link.stories.js
  react/src/components/molecules/Link/index.js
  react/src/components/organisms/GeneralTeaser/GeneralTeaser.md
  react/src/components/organisms/GeneralTeaser/GeneralTeaser.stories.js
  react/src/components/organisms/GeneralTeaser/index.js
  react/src/components/organisms/GeneralTeaser/style.scss
  react/src/index.js
Labels: Ready For Internal Review

#254 Update mf/react to work with shared assets
  .circleci/config.yml
  changelogs/DP-10392.txt
  react/.eslintrc.json
  react/.storybook/webpack.config.js
  react/nwb.config.js
  react/package-lock.json
  react/package.json
  react/src/assets
  react/src/components/atoms/media/SiteLogo/index.js
  react/src/components/organisms/Footer/Footer.stories.js
  react/src/components/organisms/Footer/index.js
  react/src/components/organisms/GeneralTeaser/GeneralTeaser.stories.js
  react/src/index.scss
Labels: external review

#248 DP-10368 Fixed SearchBanner molecule filters position when no tabs
  changelogs/DP-10368.txt
  react/src/components/organisms/SearchBanner/index.js
  react/src/components/organisms/SearchBanner/style.scss
Labels: Ready For Internal Review

#259 React/searchbanner refactor
  changelogs/searchbanner-refactor.txt
  react/backstop/data/bitmaps_reference/vrt_molecules_HeaderSearch_HeaderSearch_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/vrt_molecules_HeaderSearch_HeaderSearch_0_document_1_tablet.png
  react/backstop/data/bitmaps_reference/vrt_molecules_HeaderSearch_HeaderSearch_with_postInputFilter_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/vrt_molecules_HeaderSearch_HeaderSearch_with_postInputFilter_0_document_1_tablet.png
  react/backstop/data/bitmaps_reference/vrt_organisms_Header_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/vrt_organisms_Header_0_document_1_tablet.png
  react/backstop/data/bitmaps_reference/vrt_organisms_SearchBanner_SearchBanner_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/vrt_organisms_SearchBanner_SearchBanner_0_document_1_tablet.png
  react/backstop/data/bitmaps_reference/vrt_organisms_SearchBanner_SearchBanner_with_postInputFilter_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/vrt_organisms_SearchBanner_SearchBanner_with_postInputFilter_0_document_1_tablet.png
  react/src/components/atoms/forms/InputTextTypeAhead/InputTextTypeAhead.knobs.options.js
  react/src/components/atoms/forms/SelectBox/SelectBox.knobs.options.js
  react/src/components/atoms/forms/SelectBox/style.scss
  react/src/components/molecules/HeaderSearch/HeaderSearch.scss
  react/src/components/molecules/HeaderSearch/HeaderSearch.stories.js
  react/src/components/molecules/HeaderSearch/index.js
  react/src/components/molecules/IconLink/index.js
  react/src/components/organisms/SearchBanner/SearchBanner.stories.js
  react/src/components/organisms/SearchBanner/style.scss
  react/src/components/styles/_global.scss
  react/src/components/utilities/componentPropTypeCheck.js
  react/src/index.scss
Labels: external review, internal review

#262 Switches the Link component arrow icon props to numbers from strings.
  react/src/components/molecules/Link/index.js
Labels: external review

#264 React/configureable site logo
  changelogs/configureable-siteLogo.txt
  react/src/components/atoms/media/SiteLogo/SiteLogo.stories.js
  react/src/components/atoms/media/SiteLogo/index.js
Labels: external review

#274 DP-10502: Adding ButtonFixedFeedback component
  changelogs/DP-10502.text
  react/backstop/data/bitmaps_reference/vrt_atoms_buttons_ButtonFixedFeedback_0_document_0_small_atom.png
  react/src/components/atoms/buttons/ButtonFixedFeedback/ButtonFixedFeedback.stories.js
  react/src/components/atoms/buttons/ButtonFixedFeedback/index.js
  react/src/components/atoms/buttons/ButtonFixedFeedback/style.scss
  react/src/index.js
Labels: internal review

#261 add primary and secondary theme to button search
  assets/scss/01-atoms/_button-search.scss
  assets/scss/02-molecules/_header-search.scss
  assets/scss/03-organisms/_header.scss
  assets/scss/03-organisms/_organization-navigation.scss
  changelogs/DP-10514.txt
  patternlab/styleguide/source/_data/headerSearch.json
  patternlab/styleguide/source/_patterns/01-atoms/01-buttons/button-search-as-secondary.md
  patternlab/styleguide/source/_patterns/01-atoms/01-buttons/button-search.md
  patternlab/styleguide/source/_patterns/01-atoms/01-buttons/button-search.twig
  patternlab/styleguide/source/_patterns/01-atoms/01-buttons/button-search~as-secondary.json
  patternlab/styleguide/source/_patterns/02-molecules/header-search.twig
  react/backstop/data/bitmaps_reference/vrt_atoms_buttons_ButtonSearch_0_document_0_small_atom.png
  react/backstop/data/bitmaps_reference/vrt_molecules_HeaderSearch_HeaderSearch_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/vrt_molecules_HeaderSearch_HeaderSearch_0_document_1_tablet.png
  react/backstop/data/bitmaps_reference/vrt_molecules_HeaderSearch_HeaderSearch_with_postInputFilter_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/vrt_molecules_HeaderSearch_HeaderSearch_with_postInputFilter_0_document_1_tablet.png
  react/backstop/data/bitmaps_reference/vrt_organisms_SearchBanner_SearchBanner_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/vrt_organisms_SearchBanner_SearchBanner_0_document_1_tablet.png
  react/backstop/data/bitmaps_reference/vrt_organisms_SearchBanner_SearchBanner_with_postInputFilter_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/vrt_organisms_SearchBanner_SearchBanner_with_postInputFilter_0_document_1_tablet.png
  react/src/components/atoms/buttons/ButtonWithIcon/ButtonWithIcon.knob.options.js
  react/src/components/atoms/buttons/ButtonWithIcon/ButtonWithIcon.stories.js
  react/src/components/atoms/buttons/ButtonWithIcon/index.js
  react/src/components/atoms/buttons/ButtonWithIcon/style.scss
  react/src/components/molecules/HeaderSearch/HeaderSearch.scss
  react/src/components/molecules/HeaderSearch/HeaderSearch.stories.js
  react/src/components/molecules/HeaderSearch/index.js
  react/src/components/organisms/Header/Header.stories.js
Labels: external review, internal review

#198 DP-10057: Mayflower React: Port Tooltip Molecule in Mayflower React
  changelogs/DP-10057.txt
  react/backstop/data/bitmaps_reference/mayflower-react-atoms_atoms_icons_SvgQuestionMark_0_document_0_small_atom.png
  react/backstop/data/bitmaps_reference/mayflower-react_molecules_Tooltip_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/mayflower-react_molecules_Tooltip_0_document_1_tablet.png
  react/backstop/data/bitmaps_reference/vrt_atoms_icons_Icon_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/vrt_atoms_icons_Icon_0_document_1_tablet.png
  react/backstop/data/bitmaps_reference/vrt_molecules_Tooltip_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/vrt_molecules_Tooltip_0_document_1_tablet.png
  react/src/components/atoms/icons/Icon/Icon.knob.options.js
  react/src/components/atoms/icons/Icon/assets/questionmark.svg
  react/src/components/molecules/Tooltip/Tooltip.knob.options.js
  react/src/components/molecules/Tooltip/Tooltip.md
  react/src/components/molecules/Tooltip/Tooltip.stories.js
  react/src/components/molecules/Tooltip/index.js
  react/src/components/molecules/Tooltip/style.scss
  react/src/index.js
Labels: external review

#277 React/filter box refactor
  changelogs/DP-10521.txt
  react/backstop/data/bitmaps_reference/vrt_organisms_FilterBox_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/vrt_organisms_FilterBox_0_document_1_tablet.png
  react/src/components/organisms/FilterBox/FilterBox.stories.js
  react/src/components/organisms/FilterBox/index.js
  react/src/components/organisms/FilterBox/style.scss
  react/src/components/organisms/SearchBanner/SearchBanner.stories.js
  react/src/components/utilities/componentPropTypeCheck.js
Labels: external review, internal review
