Repository massgov/mayflower, pull requests merged in 2018-10, with the labels that each got.

#275 React/accordion wrapper child validation
  changelogs/AccordionWrapper-PropType.txt
  react/src/components/organisms/AccordionWrapper/index.js
Labels: external review

#286 DP-10441: Add HeaderSlim in Mayflower-react.
  assets/scss/03-organisms/_header-slim.scss
  changelogs/DP-10441.txt
  react/backstop/data/bitmaps_reference/vrt_organisms_HeaderSlim_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/vrt_organisms_HeaderSlim_0_document_1_tablet.png
  react/src/components/atoms/media/SiteLogo/index.js
  react/src/components/organisms/HeaderSlim/HeaderSlim.stories.js
  react/src/components/organisms/HeaderSlim/index.js
  react/src/components/organisms/HeaderSlim/style.scss
  react/src/index.js
Labels: React, Ready For Internal Review

#285 DP-10440: FooterSlim Component
  assets/scss/03-organisms/_footer-slim.scss
  changelogs/DP-10440.txt
  react/backstop/data/bitmaps_reference/vrt_organisms_FooterSlim_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/vrt_organisms_FooterSlim_0_document_1_tablet.png
  react/package-lock.json
  react/src/components/organisms/FooterSlim/FooterSlim.md
  react/src/components/organisms/FooterSlim/FooterSlim.stories.js
  react/src/components/organisms/FooterSlim/index.js
  react/src/components/organisms/FooterSlim/style.scss
  react/src/index.js
Labels: Ready For Internal Review

#296 React/dp 10679 filter box a11y
  changelogs/DP-10679.txt
  changelogs/fix-filterbox.txt
  react/src/components/organisms/FilterBox/FilterBox.stories.js
  react/src/components/organisms/FilterBox/index.js
  react/src/components/organisms/SearchBanner/SearchBanner.stories.js
  react/src/components/organisms/SearchBanner/index.js
Labels: internal review

#299 React/dp 10678 tabs a11y aria label
  assets/scss/02-molecules/_tabs.scss
  changelogs/DP-10678.txt
  react/src/components/molecules/Tabs/Tabs.knobs.options.js
  react/src/components/molecules/Tabs/index.js
  react/src/components/molecules/Tabs/style.scss
Labels: Ready For Internal Review

#289 Add react tables
  assets/scss/05-dataviz/_datatable.scss
  changelogs/add-react-table.txt
  react/backstop/data/bitmaps_reference/vrt_dataviz_DataTable_DataTable_Simple_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/vrt_dataviz_DataTable_DataTable_Simple_0_document_1_tablet.png
  react/backstop/data/bitmaps_reference/vrt_dataviz_DataTable_DataTable_with_Filter_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/vrt_dataviz_DataTable_DataTable_with_Filter_0_document_1_tablet.png
  react/package-lock.json
  react/package.json
  react/src/components/dataviz/DataTable/DataTable.md
  react/src/components/dataviz/DataTable/DataTable.stories.js
  react/src/components/dataviz/DataTable/DataTableCounty.json
  react/src/components/dataviz/DataTable/DataTableTown.json
  react/src/components/dataviz/DataTable/index.js
  react/src/components/dataviz/DataTable/styles.scss
  react/src/components/dataviz/helper/index.js
  react/src/components/molecules/Tooltip/Tooltip.knob.options.js
  react/src/index.js
Labels: external review, internal review

#313 DP-10784: Mayflower-React: Port Listing Table in React from PL
  assets/scss/02-molecules/_listing-table.scss
  changelogs/DP-10784.txt
  react/backstop/data/bitmaps_reference/vrt_molecules_ListingTable_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/vrt_molecules_ListingTable_0_document_1_tablet.png
  react/src/components/molecules/ListingTable/ListingTable.md
  react/src/components/molecules/ListingTable/ListingTable.stories.js
  react/src/components/molecules/ListingTable/index.js
  react/src/components/molecules/ListingTable/style.scss
Labels: Ready For Internal Review

#311 DP-10765: Porting Table of Contents Hierarchy component.
  assets/scss/03-organisms/_table-of-contents-hierarchy.scss
  react/backstop/data/bitmaps_reference/.DS_Store
  react/backstop/data/bitmaps_reference/vrt_organisms_TableofContents_TableofContents_with_ColoredHeading_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/vrt_organisms_TableofContents_TableofContents_with_ColoredHeading_0_document_1_tablet.png
  react/backstop/data/bitmaps_reference/vrt_organisms_TableofContents_TableofContents_with_SidebarHeading_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/vrt_organisms_TableofContents_TableofContents_with_SidebarHeading_0_document_1_tablet.png
  react/src/components/animations/Collapse/index.js
  react/src/components/organisms/TableofContents/TableofContents.md
  react/src/components/organisms/TableofContents/TableofContents.stories.js
  react/src/components/organisms/TableofContents/index.js
  react/src/components/organisms/TableofContents/style.scss
  react/src/index.js
Labels: Ready For Internal Review

#330 (React) DP-10895: Fix for pageflipper bug
  changelogs/DP-10895.txt
  react/src/components/organisms/PageFlipper/index.js
Labels: external review

#329 React/page header scss
  changelogs/PageHeader-scss.txt
  react/src/components/organisms/PageHeader/index.js
  react/src/components/organisms/PageHeader/style.scss
Labels: external review, internal review

#297 DP-10244: Mayflower React: Import Componentized SCSS (molecules)
  assets/scss/02-molecules/_header-search.scss
  react/backstop/data/bitmaps_reference/vrt_molecules_HeaderSearch_HeaderSearch_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/vrt_molecules_HeaderSearch_HeaderSearch_with_postInputFilter_0_document_0_phone.png
  react/src/components/molecules/CalloutLink/index.js
  react/src/components/molecules/CalloutLink/style.scss
  react/src/components/molecules/ContactGroup/index.js
  react/src/components/molecules/ContactGroup/style.scss
  react/src/components/molecules/DateRange/index.js
  react/src/components/molecules/DateRange/style.scss
  react/src/components/molecules/FooterLinks/index.js
  react/src/components/molecules/FooterLinks/style.scss
  react/src/components/molecules/HeaderSearch/index.js
  react/src/components/molecules/HeaderSearch/style.scss
  react/src/components/molecules/ImagePromo/style.scss
  react/src/components/molecules/Link/index.js
  react/src/components/molecules/Link/style.scss
  react/src/components/molecules/MainNav/style.scss
  react/src/components/molecules/OrgSelector/style.scss
  react/src/components/molecules/Pagination/index.js
  react/src/components/molecules/Pagination/style.scss
  react/src/components/molecules/PressTeaser/index.js
  react/src/components/molecules/PressTeaser/style.scss
  react/src/components/molecules/SocialLinks/index.js
  react/src/components/molecules/SocialLinks/style.scss
  react/src/components/molecules/SortResults/index.js
  react/src/components/molecules/SortResults/style.scss
  react/src/components/organisms/Header/styles.scss
  react/src/index.scss
Labels: Ready For Internal Review

#340 Footer extension
  changelogs/DP-11038.txt
  react/backstop/data/bitmaps_reference/vrt_organisms_Footer_Footer_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/vrt_organisms_Footer_Footer_0_document_1_tablet.png
  react/backstop/data/bitmaps_reference/vrt_organisms_Footer_Footer_with_live_JSON_0_document_1_tablet.png
  react/src/components/molecules/FooterLinks/index.js
  react/src/components/molecules/FooterLinks/style.scss
  react/src/components/organisms/Footer/Footer.stories.js
  react/src/components/organisms/Footer/index.js
Labels: external review, internal review
