Repository massgov/mayflower, pull requests merged in 2018-08, with the labels that each got.

#75 Fix vulnerability
  changelogs/dependency-update.txt
  patternlab/styleguide/package-lock.json
  patternlab/styleguide/package.json
  patternlab/styleguide/yarn.lock
  react/package-lock.json
  react/package.json
Labels: WIP - Do not merge

#97 DP-9750: Adds HelperText form atom component to Mayflower React library
  changelogs/DP-9750.txt
  react/src/components/atoms/forms/HelperText/HelperText.knobs.options.js
  react/src/components/atoms/forms/HelperText/HelperText.md
  react/src/components/atoms/forms/HelperText/HelperText.stories.js
  react/src/components/atoms/forms/HelperText/index.js
  react/src/index.js
Labels: internal review

#107 DP-9527 set up React build
  .circleci/config.yml
  changelogs/DP-9527.txt
  react/package-lock.json
  react/package.json
Labels: external review

#121 Revert our nwb dep to "0.21.x" to fix the build for now
  react/package-lock.json
  react/package.json
Labels: internal review

#127 Install pip, awscli in react_deploy_tag
  .circleci/config.yml
Labels: internal review

#81 refactor ButtonWIthIcon to replace ButtonSearch
  changelogs/react-button-refactor.txt
  react/src/components/atoms/buttons/ButtonSearch/ButtonSearch.md
  react/src/components/atoms/buttons/ButtonSearch/ButtonSearch.stories.js
  react/src/components/atoms/buttons/ButtonSearch/index.js
  react/src/components/atoms/buttons/ButtonWithIcon/ButtonWithIcon.knob.options.js
  react/src/components/atoms/buttons/ButtonWithIcon/ButtonWithIcon.md
  react/src/components/atoms/buttons/ButtonWithIcon/ButtonWithIcon.stories.js
  react/src/components/atoms/buttons/ButtonWithIcon/index.js
  react/src/components/molecules/HeaderSearch/HeaderSearch.scss
  react/src/components/molecules/HeaderSearch/HeaderSearch.stories.js
  react/src/components/molecules/HeaderSearch/index.js
  react/src/components/molecules/SearchBannerForm/index.js
  react/src/index.js
Labels: internal review

#164 React/update footer info
  changelogs/DP-10069.txt
  patternlab/styleguide/source/_patterns/03-organisms/by-template/footer.md
  react/src/components/organisms/Footer/Footer.md
  react/src/components/organisms/Footer/Footer.stories.js
  react/src/components/organisms/Footer/index.js
Labels: external review

#85 React: Add Standard Accordion Components to Mayflower React
  assets/scss/02-molecules/_accordion-item.scss
  assets/scss/03-organisms/_accordion-wrapper.scss
  changelogs/DP-9981.txt
  react/backstop/backstop.js
  react/backstop/data/.DS_Store
  react/backstop/data/bitmaps_reference/mayflower-react-atoms_atoms_icons_SvgCircleChevron_0_document_0_small_atom.png
  react/backstop/data/bitmaps_reference/mayflower-react_atoms_media_Image_0_document_1_tablet.png
  react/backstop/data/bitmaps_reference/mayflower-react_molecules_AccordionItem_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/mayflower-react_molecules_AccordionItem_0_document_1_tablet.png
  react/backstop/data/bitmaps_reference/mayflower-react_molecules_CalloutLink_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/mayflower-react_molecules_CalloutLink_0_document_1_tablet.png
  react/backstop/data/bitmaps_reference/mayflower-react_molecules_ImagePromo_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/mayflower-react_molecules_ImagePromo_0_document_1_tablet.png
  react/backstop/data/bitmaps_reference/mayflower-react_molecules_Pagination_0_document_1_tablet.png
  react/backstop/data/bitmaps_reference/mayflower-react_molecules_SearchBannerForm_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/mayflower-react_molecules_SearchBannerForm_0_document_1_tablet.png
  react/backstop/data/bitmaps_reference/mayflower-react_molecules_SortResults_0_document_1_tablet.png
  react/backstop/data/bitmaps_reference/mayflower-react_molecules_TypeAheadDropdown_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/mayflower-react_molecules_TypeAheadDropdown_0_document_1_tablet.png
  react/backstop/data/bitmaps_reference/mayflower-react_organisms_AccordionWrapper_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/mayflower-react_organisms_AccordionWrapper_0_document_1_tablet.png
  react/backstop/data/bitmaps_reference/mayflower-react_organisms_Footer_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/mayflower-react_organisms_Footer_0_document_1_tablet.png
  react/backstop/data/bitmaps_reference/mayflower-react_organisms_LinkList_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/mayflower-react_organisms_LinkList_0_document_1_tablet.png
  react/backstop/listComponents.js
  react/backstop/listDirs.js
  react/package-lock.json
  react/package.json
  react/src/components/animations/Collapse/index.js
  react/src/components/atoms/Divider/Divider.stories.js
  react/src/components/atoms/headings/CompHeading/CompHeading.knob.options.js
  react/src/components/atoms/headings/Heading/index.js
  react/src/components/atoms/icons/SvgCircleChevron/SvgCircleChevron.stories.js
  react/src/components/atoms/icons/SvgCircleChevron/index.js
  react/src/components/molecules/AccordionItem/AccordionItem.md
  react/src/components/molecules/AccordionItem/AccordionItem.stories.js
  react/src/components/molecules/AccordionItem/index.js
  react/src/components/molecules/AccordionItem/style.scss
  react/src/components/molecules/CalloutLink/CalloutLink.stories.js
  react/src/components/molecules/ImagePromo/ImagePromo.stories.js
  react/src/components/molecules/ResultsHeading/ResultsHeading.stories.js
  react/src/components/molecules/SearchBannerForm/SearchBannerForm.stories.js
  react/src/components/organisms/AccordionWrapper/AccordionWrapper.md
  react/src/components/organisms/AccordionWrapper/AccordionWrapper.stories.js
  react/src/components/organisms/AccordionWrapper/index.js
  react/src/components/organisms/AccordionWrapper/style.scss
  react/src/components/organisms/Footer/Footer.stories.js
  react/src/index.js
Labels: internal review

#159 [React] Error Message component
  assets/images/svg-icons/close.svg
  assets/images/svg-icons/help.svg
  assets/images/svg-icons/input-success.svg
  assets/scss/01-atoms/_error-msg.scss
  changelogs/DP-10028.txt
  react/backstop/data/bitmaps_reference/mayflower-react-atoms_atoms_forms_ErrorMessage_0_document_0_small_atom.png
  react/backstop/data/bitmaps_reference/mayflower-react-atoms_atoms_icons_SvgInputError_0_document_0_small_atom.png
  react/backstop/data/bitmaps_reference/mayflower-react-atoms_atoms_icons_SvgInputSuccess_0_document_0_small_atom.png
  react/package-lock.json
  react/src/components/atoms/forms/ErrorMessage/ErrorMessage.knobs.options.js
  react/src/components/atoms/forms/ErrorMessage/ErrorMessage.md
  react/src/components/atoms/forms/ErrorMessage/ErrorMessage.stories.js
  react/src/components/atoms/forms/ErrorMessage/index.js
  react/src/components/atoms/forms/ErrorMessage/style.scss
  react/src/components/atoms/forms/HelperText/index.js
  react/src/components/atoms/icons/SvgInputError/SvgInputError.md
  react/src/components/atoms/icons/SvgInputError/SvgInputError.stories.js
  react/src/components/atoms/icons/SvgInputError/index.js
  react/src/components/atoms/icons/SvgInputSuccess/SvgInputSuccess.md
  react/src/components/atoms/icons/SvgInputSuccess/SvgInputSuccess.stories.js
  react/src/components/atoms/icons/SvgInputSuccess/index.js
  react/src/index.js
Labels: external review

#194 DP-10029 - Update styles to fix margin on image without requiring it to be linked.
  assets/scss/03-organisms/_location-listing.scss
  changelogs/DP-10029.txt
Labels: Ready For Internal Review
