Repository massgov/mayflower, pull requests merged in 2018-02, with the labels that each got.

#683 DP-6350 [a11y] Change search query field place holder text in location/event lists
  styleguide/source/_patterns/05-pages/event-listing.json
  styleguide/source/_patterns/05-pages/location-listing.json
Labels: WIP - Do Not Merge

#699 DP-1553 [a11y] Correct aria role value
  styleguide/source/_patterns/03-organisms/by-template/illustrated-header.twig
Labels: quick-fix

#691 DP-2403 [a11y] Text info. for the social media icons in the footer
  styleguide/source/_patterns/02-molecules/social-links.twig
Labels: quick-fix

#676 DP-3198 a11y Keyboard focus indicator usability for main menus
  styleguide/source/_patterns/02-molecules/main-nav.twig
Labels: quick-fix

#708 Adding changelog process to Mayflower
  .github/PULL_REQUEST_TEMPLATE.md
  changelogs/template.txt
  docs/change-log-instructions.md
  docs/release.md
  release-notes.md
Labels: WIP - Do Not Merge, docs

#687 DP-2082 [a11y] Add intuitive infor to the + symbols for accordion buttons
  styleguide/source/_patterns/02-molecules/contact-us.twig
  styleguide/source/assets/js/modules/accordions.js
  styleguide/source/assets/scss/02-molecules/_contact-us.scss
  styleguide/source/assets/scss/06-theme/02-molecules/_contact-us.scss
Labels: quick-fix
