Repository massgov/mayflower, pull requests merged in 2019-11, with the labels that each got.

#823 (React) DP-16483: Collapse animation ie11 fix
  changelogs/DP-16483.md
  react/src/components/animations/Collapse/index.js
Labels: React, internal review

#818 DP-16457 Key message subtitle
  assets/scss/00-base/mixins/_ma-typography.scss
  assets/scss/01-atoms/global/_elements.scss
  assets/scss/03-organisms/_key-message.scss
  changelogs/DP-16457.md
  patternlab/backstopjs/reference/regression_page_marketing-campaign-as-solid_0_document_0_phone.png
  patternlab/backstopjs/reference/regression_page_marketing-campaign-as-solid_0_document_1_tablet.png
  patternlab/backstopjs/reference/regression_page_marketing-campaign_0_document_0_phone.png
  patternlab/backstopjs/reference/regression_page_marketing-campaign_0_document_1_tablet.png
  patternlab/styleguide/source/_patterns/03-organisms/by-template/key-message.twig
  patternlab/styleguide/source/_patterns/05-pages/marketing-campaign.json
  patternlab/styleguide/source/_patterns/05-pages/marketing-campaign~as-solid.json
Labels: external review, internal review, patternlab

#824 Patternlab/DP-16457: Key message button spacing fix
  assets/scss/03-organisms/_key-message.scss
  changelogs/DP-16457-fix.md
  patternlab/styleguide/source/_patterns/03-organisms/by-template/key-message.twig
Labels: external review, internal review

#825 Mayflower Release 9.31.0
  CHANGELOG.md
  assets/scss/00-base/mixins/_ma-typography.scss
  assets/scss/01-atoms/global/_elements.scss
  assets/scss/03-organisms/_key-message.scss
  patternlab/backstopjs/reference/regression_page_marketing-campaign-as-solid_0_document_0_phone.png
  patternlab/backstopjs/reference/regression_page_marketing-campaign-as-solid_0_document_1_tablet.png
  patternlab/backstopjs/reference/regression_page_marketing-campaign_0_document_0_phone.png
  patternlab/backstopjs/reference/regression_page_marketing-campaign_0_document_1_tablet.png
  patternlab/styleguide/source/_patterns/03-organisms/by-template/key-message.twig
  patternlab/styleguide/source/_patterns/05-pages/marketing-campaign.json
  patternlab/styleguide/source/_patterns/05-pages/marketing-campaign~as-solid.json
  react/src/components/animations/Collapse/index.js
Labels: internal review

#826 Sync Develop with Master (Mayflower Release 9.31.0)
  CHANGELOG.md
  changelogs/DP-16457-fix.md
  changelogs/DP-16457.md
  changelogs/DP-16483.md
Labels: internal review

#821 DP-16313 [a11y] Campaign video
  assets/scss/01-atoms/_video.scss
  changelogs/DP-16313.md
  patternlab/styleguide/source/_patterns/01-atoms/09-media/video.json
  patternlab/styleguide/source/_patterns/01-atoms/09-media/video.twig
  patternlab/styleguide/source/_patterns/03-organisms/by-template/campaign-video.json
  patternlab/styleguide/source/_patterns/05-pages/marketing-campaign.json
  patternlab/styleguide/source/_patterns/05-pages/marketing-campaign~as-solid.json
Labels: external review, internal review

#829 React/DP-12195: Address AccordionItem a11y issue
  changelogs/DP-12195.md
  react/src/components/molecules/AccordionItem/AccordionItem.stories.js
  react/src/components/molecules/AccordionItem/index.js
  react/src/components/organisms/AccordionWrapper/AccordionWrapper.stories.js
Labels: internal review

#828 react/DP-14222: Makes it possible to render render with/without UtilityNav and/or MainNav content
  assets/scss/03-organisms/_header.scss
  changelogs/DP-14222.md
  react/backstop/data/bitmaps_reference/vrt_organisms_Header_Header_with_MainNav__UtilityNav_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/vrt_organisms_Header_Header_with_MainNav__UtilityNav_0_document_1_tablet.png
  react/backstop/data/bitmaps_reference/vrt_organisms_Header_Header_without_MainNav_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/vrt_organisms_Header_Header_without_MainNav_0_document_1_tablet.png
  react/backstop/data/bitmaps_reference/vrt_organisms_Header_Header_without_MainNav_UtilityNav__Search_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/vrt_organisms_Header_Header_without_MainNav_UtilityNav__Search_0_document_1_tablet.png
  react/backstop/data/bitmaps_reference/vrt_organisms_Header_Header_without_UtilityNav_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/vrt_organisms_Header_Header_without_UtilityNav_0_document_1_tablet.png
  react/src/components/organisms/Header/Header.stories.js
  react/src/components/organisms/Header/index.js
Labels: internal review

#832 Mayflower Release 9.32.0
  CHANGELOG.md
  assets/scss/01-atoms/_video.scss
  assets/scss/03-organisms/_header.scss
  patternlab/styleguide/source/_patterns/01-atoms/09-media/video.json
  patternlab/styleguide/source/_patterns/01-atoms/09-media/video.twig
  patternlab/styleguide/source/_patterns/03-organisms/by-template/campaign-video.json
  patternlab/styleguide/source/_patterns/05-pages/marketing-campaign.json
  patternlab/styleguide/source/_patterns/05-pages/marketing-campaign~as-solid.json
  react/backstop/data/bitmaps_reference/vrt_organisms_Header_Header_with_MainNav__UtilityNav_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/vrt_organisms_Header_Header_with_MainNav__UtilityNav_0_document_1_tablet.png
  react/backstop/data/bitmaps_reference/vrt_organisms_Header_Header_without_MainNav_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/vrt_organisms_Header_Header_without_MainNav_0_document_1_tablet.png
  react/backstop/data/bitmaps_reference/vrt_organisms_Header_Header_without_MainNav_UtilityNav__Search_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/vrt_organisms_Header_Header_without_MainNav_UtilityNav__Search_0_document_1_tablet.png
  react/backstop/data/bitmaps_reference/vrt_organisms_Header_Header_without_UtilityNav_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/vrt_organisms_Header_Header_without_UtilityNav_0_document_1_tablet.png
  react/src/components/molecules/AccordionItem/AccordionItem.stories.js
  react/src/components/molecules/AccordionItem/index.js
  react/src/components/organisms/AccordionWrapper/AccordionWrapper.stories.js
  react/src/components/organisms/Header/Header.stories.js
  react/src/components/organisms/Header/index.js
  react/src/components/organisms/UtilityNav/index.js
Labels: internal review

#833 Sync Develop with Master (Release 9.32.0)
  CHANGELOG.md
  changelogs/DP-11663.md
  changelogs/DP-12195.md
  changelogs/DP-14222.md
  changelogs/DP-16313.md
Labels: internal review

#836 (React) DP-11777: Enable focus in a tab's content
  changelogs/DP-11777.md
  react/src/components/organisms/TabContainer/index.js
Labels: internal review
