Repository massgov/mayflower, pull requests merged in 2019-01, with the labels that each got.

#394 [React] DP-11888: Budget & Mayflower: Tabs & Anchor Link.
  changelogs/DP-11888.txt
  react/src/components/organisms/TabContainer/index.js
  react/src/components/organisms/TabContainer/tab.js
Labels: React, Ready For Internal Review, external review

#385 React DP-11634: MainNav a11y
  assets/scss/02-molecules/_main-nav.scss
  changelogs/DP-11634.txt
  react/package-lock.json
  react/package.json
  react/src/components/atoms/icons/Icon/index.js
  react/src/components/molecules/MainNav/index.js
  react/src/components/molecules/MainNav/styles.scss
  react/src/components/organisms/PageHeader/index.js
  react/src/components/organisms/TeaserListing/TeaserListing.knob.options.js
Labels: external review

#395 Release 8.17.0
  CHANGELOG.md
  assets/scss/02-molecules/_main-nav.scss
  react/package-lock.json
  react/package.json
  react/src/components/atoms/icons/Icon/index.js
  react/src/components/molecules/MainNav/index.js
  react/src/components/molecules/MainNav/styles.scss
  react/src/components/organisms/PageHeader/index.js
  react/src/components/organisms/TabContainer/index.js
  react/src/components/organisms/TabContainer/tab.js
  react/src/components/organisms/TeaserListing/TeaserListing.knob.options.js
Labels: internal review

#397 [React] DP-12012: Enable to the footnote atom to render html
  assets/scss/01-atoms/_footnote.scss
  changelogs/DP-12012.txt
  react/backstop/data/bitmaps_reference/vrt_atoms_links_FootNoteLink_0_document_0_small_atom.png
  react/backstop/data/bitmaps_reference/vrt_atoms_links_FootNote_0_document_0_small_atom.png
  react/package-lock.json
  react/src/components/atoms/links/FootNote/FootNote.stories.js
  react/src/components/atoms/links/FootNote/index.js
  react/src/components/atoms/links/FootNoteLink/FootNoteLink.stories.js
  react/src/components/organisms/TabContainer/tab.js
Labels: external review

#398 Release 8.18.0
  CHANGELOG.md
  assets/scss/01-atoms/_decorative-link.scss
  assets/scss/01-atoms/_footnote.scss
  assets/scss/03-organisms/_about-section.scss
  assets/scss/03-organisms/_person-card.scss
  assets/scss/03-organisms/_pullquote.scss
  assets/scss/08-print/_print.scss
  patternlab/backstopjs/reference/regression_page_organization-elected-official_0_document_0_phone.png
  patternlab/backstopjs/reference/regression_page_organization-elected-official_0_document_1_tablet.png
  patternlab/styleguide/source/_patterns/03-organisms/by-author/pullquote.twig
  patternlab/styleguide/source/_patterns/03-organisms/by-author/rich-text.twig
  patternlab/styleguide/source/_patterns/03-organisms/by-template/header-alert.twig
  react/backstop/data/bitmaps_reference/vrt_atoms_links_FootNoteLink_0_document_0_small_atom.png
  react/backstop/data/bitmaps_reference/vrt_atoms_links_FootNote_0_document_0_small_atom.png
  react/backstop/data/bitmaps_reference/vrt_organisms_GeneralTeaser_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/vrt_organisms_GeneralTeaser_0_document_1_tablet.png
  react/backstop/data/bitmaps_reference/vrt_organisms_TableofContents_TableofContents_with_ColoredHeading_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/vrt_organisms_TableofContents_TableofContents_with_ColoredHeading_0_document_1_tablet.png
  react/backstop/data/bitmaps_reference/vrt_organisms_TableofContents_TableofContents_with_SidebarHeading_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/vrt_organisms_TableofContents_TableofContents_with_SidebarHeading_0_document_1_tablet.png
  react/package-lock.json
  react/src/components/atoms/links/DecorativeLink/index.js
  react/src/components/atoms/links/FootNote/FootNote.stories.js
  react/src/components/atoms/links/FootNote/index.js
  react/src/components/atoms/links/FootNoteLink/FootNoteLink.stories.js
  react/src/components/organisms/TabContainer/tab.js
Labels: internal review

#399 Sync Master back Into Develop (Release 8.18.0)
  CHANGELOG.md
  changelogs/DP-11400.txt
  changelogs/DP-11682.txt
  changelogs/DP-12012.txt
  changelogs/DP-5230.txt
  changelogs/DP-5232.txt
  changelogs/DP-9183.txt
  changelogs/DP-9185.txt
  changelogs/DP-9775.txt
Labels: internal review

#404 React/DP-11128: Fix image promo title in IE11
  changelogs/DP-11128.txt
  react/backstop/data/bitmaps_reference/vrt_molecules_ImagePromo_ImagePromo_as_orgInfo_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/vrt_molecules_ImagePromo_ImagePromo_as_orgInfo_0_document_1_tablet.png
  react/src/components/molecules/ImagePromo/style.scss
Labels: React, external review, internal review

#408 React/DP-12217: Conditionally render main nav link
  changelogs/DP-12217.txt
  react/src/components/molecules/MainNav/MainNav.knob.options.js
  react/src/components/molecules/MainNav/index.js
  react/src/components/molecules/MainNav/style.scss
Labels: external review, internal review

#409 Mayflower Release 8.19.0
  CHANGELOG.md
  assets/scss/01-atoms/_decorative-link.scss
  patternlab/styleguide/source/assets/js/modules/locationListing.js
  react/backstop/data/bitmaps_reference/vrt_molecules_ImagePromo_ImagePromo_as_orgInfo_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/vrt_molecules_ImagePromo_ImagePromo_as_orgInfo_0_document_1_tablet.png
  react/backstop/data/bitmaps_reference/vrt_organisms_Header_0_document_1_tablet.png
  react/backstop/data/bitmaps_reference/vrt_organisms_UtilityNav_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/vrt_organisms_UtilityNav_0_document_1_tablet.png
  react/src/components/atoms/links/DecorativeLink/index.js
  react/src/components/molecules/HeaderSearch/index.js
  react/src/components/molecules/ImagePromo/style.scss
  react/src/components/molecules/MainNav/MainNav.knob.options.js
  react/src/components/molecules/MainNav/index.js
  react/src/components/molecules/MainNav/style.scss
  react/src/components/organisms/UtilityNav/UtilityNav.knob.options.js
  react/src/components/organisms/UtilityNav/UtilityNav.stories.js
  react/src/components/organisms/UtilityNav/index.js
Labels: internal review

#415 DP-11662 utility nav container
  changelogs/DP-11662.txt
  patternlab/styleguide/source/_patterns/03-organisms/by-template/utility-nav.twig
  patternlab/styleguide/source/_patterns/03-organisms/by-template/utility-panel.twig
  react/src/components/organisms/UtilityNav/index.js
  react/src/components/organisms/UtilityPanel/index.js
Labels: external review

#416 DP-11668 main nav container
  changelogs/DP-11668.txt
  patternlab/styleguide/source/_patterns/02-molecules/main-nav.twig
  react/src/components/molecules/MainNav/index.js
Labels: external review

#424 React/dp 12318 create input radio buttons
  assets/scss/00-base/_colors.scss
  assets/scss/01-atoms/_input-radio.scss
  assets/scss/02-molecules/_input-radio-group.scss
  changelogs/DP-12318.txt
  patternlab/styleguide/source/_patterns/01-atoms/03-forms/input-radio.twig
  react/.eslintrc.json
  react/.gitignore
  react/backstop/data/bitmaps_reference/vrt_atoms_forms_InputRadio_0_document_0_small_atom.png
  react/backstop/data/bitmaps_reference/vrt_molecules_InputRadioGroup_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/vrt_molecules_InputRadioGroup_0_document_1_tablet.png
  react/package-lock.json
  react/package.json
  react/src/components/atoms/forms/InputRadio/InputRadio.md
  react/src/components/atoms/forms/InputRadio/InputRadio.stories.js
  react/src/components/atoms/forms/InputRadio/index.js
  react/src/components/atoms/forms/InputRadio/style.scss
  react/src/components/atoms/forms/InputTextFuzzy/index.js
  react/src/components/molecules/InputRadioGroup/InputRadioGroup.knobs.options.js
  react/src/components/molecules/InputRadioGroup/InputRadioGroup.md
  react/src/components/molecules/InputRadioGroup/InputRadioGroup.stories.js
  react/src/components/molecules/InputRadioGroup/index.js
  react/src/components/molecules/InputRadioGroup/style.scss
  react/src/components/molecules/ListingTable/index.js
  react/src/components/organisms/Teaser/index.js
  react/src/components/organisms/TeaserListing/index.js
  react/src/index.js
Labels: external review, internal review

#418 Dp 12320 create callout alert
  assets/scss/03-organisms/_callout-alert.scss
  changelogs/DP-12320.txt
  react/backstop/data/bitmaps_reference/vrt_atoms_icons_Icon_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/vrt_atoms_icons_Icon_0_document_1_tablet.png
  react/backstop/data/bitmaps_reference/vrt_organisms_CalloutAlert_CalloutAlert_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/vrt_organisms_CalloutAlert_CalloutAlert_0_document_1_tablet.png
  react/backstop/data/bitmaps_reference/vrt_organisms_CalloutAlert_CalloutAlert_with_real_data_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/vrt_organisms_CalloutAlert_CalloutAlert_with_real_data_0_document_1_tablet.png
  react/src/components/atoms/icons/Icon/Icon.knob.options.js
  react/src/components/atoms/icons/Icon/Icon.stories.js
  react/src/components/atoms/icons/Icon/assets/alert.svg
  react/src/components/atoms/icons/Icon/index.js
  react/src/components/organisms/CalloutAlert/CalloutAlert.md
  react/src/components/organisms/CalloutAlert/CalloutAlert.stories.js
  react/src/components/organisms/CalloutAlert/index.js
  react/src/components/organisms/CalloutAlert/style.scss
  react/src/index.js
Labels: external review, internal review

#419 React/DP-12293: Currency component.
  assets/scss/01-atoms/_input-currency.scss
  changelogs/DP-12293.txt
  react/backstop/data/bitmaps_reference/vrt_atoms_forms_InputCurrency_0_document_0_small_atom.png
  react/package-lock.json
  react/package.json
  react/src/components/atoms/forms/Input/context.js
  react/src/components/atoms/forms/Input/index.js
  react/src/components/atoms/forms/Input/style.scss
  react/src/components/atoms/forms/InputCurrency/InputCurrency.knobs.options.js
  react/src/components/atoms/forms/InputCurrency/InputCurrency.md
  react/src/components/atoms/forms/InputCurrency/InputCurrency.stories.js
  react/src/components/atoms/forms/InputCurrency/index.js
  react/src/components/atoms/forms/InputCurrency/style.scss
  react/src/index.js
Labels: React, Ready For Internal Review, external review

#426 Release 8.21.0
  CHANGELOG.md
  assets/scss/00-base/_colors.scss
  assets/scss/01-atoms/_input-currency.scss
  assets/scss/01-atoms/_input-radio.scss
  assets/scss/02-molecules/_input-radio-group.scss
  assets/scss/03-organisms/_callout-alert.scss
  patternlab/styleguide/source/_patterns/01-atoms/03-forms/input-radio.twig
  react/.eslintrc.json
  react/.gitignore
  react/backstop/data/bitmaps_reference/vrt_atoms_forms_InputCurrency_0_document_0_small_atom.png
  react/backstop/data/bitmaps_reference/vrt_atoms_forms_InputRadio_0_document_0_small_atom.png
  react/backstop/data/bitmaps_reference/vrt_atoms_icons_Icon_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/vrt_atoms_icons_Icon_0_document_1_tablet.png
  react/backstop/data/bitmaps_reference/vrt_molecules_InputRadioGroup_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/vrt_molecules_InputRadioGroup_0_document_1_tablet.png
  react/backstop/data/bitmaps_reference/vrt_organisms_CalloutAlert_CalloutAlert_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/vrt_organisms_CalloutAlert_CalloutAlert_0_document_1_tablet.png
  react/backstop/data/bitmaps_reference/vrt_organisms_CalloutAlert_CalloutAlert_with_real_data_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/vrt_organisms_CalloutAlert_CalloutAlert_with_real_data_0_document_1_tablet.png
  react/package-lock.json
  react/package.json
  react/src/components/atoms/forms/Input/context.js
  react/src/components/atoms/forms/Input/index.js
  react/src/components/atoms/forms/Input/style.scss
  react/src/components/atoms/forms/InputCurrency/InputCurrency.knobs.options.js
  react/src/components/atoms/forms/InputCurrency/InputCurrency.md
  react/src/components/atoms/forms/InputCurrency/InputCurrency.stories.js
  react/src/components/atoms/forms/InputCurrency/index.js
  react/src/components/atoms/forms/InputCurrency/style.scss
  react/src/components/atoms/forms/InputRadio/InputRadio.md
  react/src/components/atoms/forms/InputRadio/InputRadio.stories.js
  react/src/components/atoms/forms/InputRadio/index.js
  react/src/components/atoms/forms/InputRadio/style.scss
  react/src/components/atoms/forms/InputTextFuzzy/index.js
  react/src/components/atoms/icons/Icon/Icon.knob.options.js
  react/src/components/atoms/icons/Icon/Icon.stories.js
  react/src/components/atoms/icons/Icon/assets/alert.svg
  react/src/components/atoms/icons/Icon/index.js
  react/src/components/molecules/InputRadioGroup/InputRadioGroup.knobs.options.js
  react/src/components/molecules/InputRadioGroup/InputRadioGroup.md
  react/src/components/molecules/InputRadioGroup/InputRadioGroup.stories.js
  react/src/components/molecules/InputRadioGroup/index.js
  react/src/components/molecules/InputRadioGroup/style.scss
  react/src/components/molecules/ListingTable/index.js
  react/src/components/organisms/CalloutAlert/CalloutAlert.md
  react/src/components/organisms/CalloutAlert/CalloutAlert.stories.js
  react/src/components/organisms/CalloutAlert/index.js
  react/src/components/organisms/CalloutAlert/style.scss
  react/src/components/organisms/Teaser/index.js
  react/src/components/organisms/TeaserListing/index.js
  react/src/index.js
Labels: external review

#432 Dp-12338: Add inline help tip organism.
  assets/scss/00-base/_colors.scss
  assets/scss/03-organisms/_help-tip.scss
  changelogs/DP-12338.txt
  package-lock.json
  react/backstop/data/bitmaps_reference/vrt_organisms_HelpTip_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/vrt_organisms_HelpTip_0_document_1_tablet.png
  react/backstop/data/bitmaps_reference/vrt_organisms_HelpTip_HelpTip_with_Children_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/vrt_organisms_HelpTip_HelpTip_with_Children_0_document_1_tablet.png
  react/backstop/data/bitmaps_reference/vrt_organisms_HelpTip_HelpTip_with_HelpText_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/vrt_organisms_HelpTip_HelpTip_with_HelpText_0_document_1_tablet.png
  react/src/components/atoms/icons/Icon/assets/close.svg
  react/src/components/organisms/HelpTip/HelpText.stories.js
  react/src/components/organisms/HelpTip/index.js
  react/src/components/organisms/HelpTip/style.scss
  react/src/index.js
Labels: React, external review

#435 DP-12428: Bug Fix React InputRadio
  changelogs/DP-12428.txt
  react/src/components/atoms/forms/InputRadio/index.js
  react/src/components/molecules/InputRadioGroup/index.js
Labels: React, external review
