Repository massgov/mayflower, pull requests merged in 2019-09, with the labels that each got.

#729 react/DP-15753: Adds new data tab icons
  changelogs/DP-15753.md
  react/backstop/data/bitmaps_reference/vrt_atoms_icons_Icon_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/vrt_atoms_icons_Icon_0_document_1_tablet.png
  react/src/components/atoms/icons/Icon/Icon.knob.options.js
  react/src/components/atoms/icons/Icon/assets/catalog.svg
  react/src/components/atoms/icons/Icon/assets/chart.svg
  react/src/components/atoms/icons/Icon/assets/data.svg
  react/src/components/atoms/icons/Icon/assets/download.svg
  react/src/components/atoms/icons/Icon/assets/expand.svg
  react/src/components/atoms/icons/Icon/assets/map.svg
  react/src/components/atoms/icons/Icon/assets/report.svg
  react/src/components/atoms/icons/Icon/assets/setting.svg
Labels: React, external review, internal review

#751 patternlab/DP-15979: Refine Campaign Features
  assets/scss/02-molecules/_campaign-feature-2up.scss
  assets/scss/02-molecules/_card.scss
  changelogs/DP-15979.md
Labels: external review, internal review, patternlab

#759 Patternlab/DP-16011 add more link to campaign features
  assets/scss/02-molecules/_campaign-feature-2up.scss
  assets/scss/03-organisms/_campaign-feature.scss
  changelogs/DP-16011.md
  patternlab/backstopjs/reference/regression_page_marketing-campaign_0_document_0_phone.png
  patternlab/backstopjs/reference/regression_page_marketing-campaign_0_document_1_tablet.png
  patternlab/styleguide/source/_patterns/03-organisms/by-template/campaign-feature.json
  patternlab/styleguide/source/_patterns/03-organisms/by-template/campaign-feature.md
  patternlab/styleguide/source/_patterns/03-organisms/by-template/campaign-feature.twig
  patternlab/styleguide/source/_patterns/05-pages/marketing-campaign.json
Labels: external review, internal review
