Repository massgov/mayflower, pull requests merged in 2019-12, with the labels that each got.

#839 React / change footnotelink ref id to classname
  changelogs/DP11765.md
  react/src/components/atoms/links/FootNote/index.js
  react/src/components/atoms/links/FootNoteLink/index.js
Labels: internal review

#817 DP-16378 Adding release branch automation
  .circleci/config.yml
  .gitignore
  CHANGELOG.md
  changelogs/DP11765.md
  changelogs/DP11765.yml
  changelogs/template.md
  changelogs/template.yml
  package-lock.json
  package.json
  patternlab/styleguide/package-lock.json
  scripts/github-tag
  scripts/release-branch.js
  yarn.lock
Labels: enhancement

#843 React / resolve console error for header searchRedirect proptype
  changelogs/DP16673.yml
  patternlab/backstopjs/reference/regression_page_location-general-content_0_document_1_tablet.png
  react/src/components/molecules/MainNav/index.js
  react/src/components/organisms/Header/Header.stories.js
  react/src/components/organisms/Header/index.js
Labels: internal review

#845 React/dp 16677 filterbox invalid proptype
  changelogs/DP16677.yml
  react/src/components/molecules/IconLink/index.js
  react/src/components/organisms/FilterBox/index.js
  react/src/components/organisms/PageFlipper/index.js
  react/src/components/organisms/TableofContents/index.js
  react/src/components/organisms/Teaser/index.js
  react/src/components/utilities/componentPropTypeCheck.js
Labels: internal review

#787 Dp 16111 multiselect dropdown
  assets/scss/01-atoms/_button-tag.scss
  assets/scss/02-molecules/_multiselect-dropdown.scss
  assets/scss/02-molecules/_results-heading.scss
  assets/scss/02-molecules/_tags.scss
  changelogs/DP-16111
  react/backstop/data/bitmaps_reference/vrt_molecules_MultiSelectDropDown_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/vrt_molecules_MultiSelectDropDown_0_document_1_tablet.png
  react/backstop/data/bitmaps_reference/vrt_molecules_ResultsHeading_ResultsHeading_with_ButtonToggle_0_document_1_tablet.png
  react/backstop/data/bitmaps_reference/vrt_molecules_Tags_Tags_with_ButtonToggle_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/vrt_molecules_Tags_Tags_with_ButtonToggle_0_document_1_tablet.png
  react/src/components/atoms/buttons/ButtonTag/index.js
  react/src/components/atoms/buttons/ButtonTag/style.scss
  react/src/components/atoms/forms/Input/index.js
  react/src/components/atoms/forms/InputCheckBox/InputCheckBox.knobs.options.js
  react/src/components/atoms/forms/InputCheckBox/InputCheckBox.stories.js
  react/src/components/atoms/forms/InputCheckBox/index.js
  react/src/components/molecules/LinkDropdown/style.scss
  react/src/components/molecules/MultiSelectDropDown/MultiSelectDropDown.stories.js
  react/src/components/molecules/MultiSelectDropDown/index.js
  react/src/components/molecules/MultiSelectDropDown/style.scss
  react/src/components/molecules/ResultsHeading/ResultsHeading.knobs.options.js
  react/src/components/molecules/ResultsHeading/ResultsHeading.stories.js
  react/src/components/molecules/ResultsHeading/index.js
  react/src/components/molecules/Tags/Tags.knobs.options.js
  react/src/components/molecules/Tags/Tags.md
  react/src/components/molecules/Tags/Tags.stories.js
  react/src/components/molecules/Tags/index.js
  react/src/components/molecules/Tags/style.scss
  react/src/index.js
Labels: external review, internal review

#842 React/dp 12168 filterbox feature description
  changelogs/DP-16111
  changelogs/DP-16111.yml
  patternlab/backstopjs/reference/regression_page_organization-lite-menu-variation_0_document_0_phone.png
  patternlab/backstopjs/reference/regression_page_organization-lite-menu-variation_0_document_1_tablet.png
  react/src/components/organisms/FilterBox/FilterBox.stories.js
  react/src/components/organisms/FilterBox/index.js
  react/src/components/organisms/FilterBox/style.scss
Labels: internal review

#858 Sync Master into Develop
  CHANGELOG.md
  changelogs/DP-16111-1.yml
  changelogs/DP-16111.yml
  changelogs/DP11765.yml
  changelogs/DP16673.yml
  changelogs/DP16677.yml
  package-lock.json
  scripts/github-tag
Labels: internal review

#860 React/dp16678 fix tab ref proptype
  changelogs/DP16678.yml
  react/src/components/organisms/TabContainer/tab.js
Labels: internal review
