Repository massgov/mayflower, pull requests merged in 2019-04, with the labels that each got.

#518 react/fix inputNumber handleAdjust logic
  changelogs/DP-13167.md
  react/src/components/atoms/forms/InputCurrency/index.js
  react/src/components/atoms/forms/InputNumber/index.js
Labels: internal review

#529 [React] DP-13409: Fix onclick function not being called in Tabs Container
  changelogs/DP-13409.md
  react/src/components/organisms/TabContainer/TabContainer.stories.js
  react/src/components/organisms/TabContainer/index.js
  react/src/components/organisms/TabContainer/tab.js
Labels: external review, internal review

#531 Mayflower 9.4.1 Release
  CHANGELOG.md
  react/src/components/atoms/forms/InputCurrency/index.js
  react/src/components/atoms/forms/InputNumber/index.js
  react/src/components/atoms/forms/InputTextFuzzy/InputTextFuzzy.stories.js
  react/src/components/atoms/forms/InputTextFuzzy/index.js
  react/src/components/organisms/TabContainer/TabContainer.stories.js
  react/src/components/organisms/TabContainer/index.js
  react/src/components/organisms/TabContainer/tab.js
Labels: internal review

#532 Sync Develop With Master for Release 9.4.1
  CHANGELOG.md
  changelogs/DP-13167.md
  changelogs/DP-13409.md
  changelogs/DP-13425.md
Labels: internal review

#533 react/DP-13450--Fix-InputCurrency-OnBlurBug
  changelogs/DP-13450.md
  react/src/components/atoms/forms/InputCurrency/index.js
Labels: internal review

#535 Release 9.4.2
  CHANGELOG.md
  react/README.md
  react/src/components/atoms/forms/InputCurrency/index.js
Labels: internal review

#505 DP-12475 Remove the indentation feature part from richText.js
  changelogs/DP-12475.md
  patternlab/styleguide/source/_patterns/03-organisms/by-author/rich-text.twig
  patternlab/styleguide/source/_patterns/05-pages/rules-of-court.json
  patternlab/styleguide/source/assets/js/index.js
  patternlab/styleguide/source/assets/js/modules/richText.js
Labels: WIP - Do not merge

#543 React: Fixes warning caused by using start instead of flex-start within FilterBox component stying.
  react/src/components/organisms/FilterBox/style.scss
Labels: React, internal review
