Repository massgov/mayflower, pull requests merged in 2019-10, with the labels that each got.

#772 Patternlab/DP-16073: Fine tune campaign page styling
  assets/scss/02-molecules/_card.scss
  assets/scss/03-organisms/_campaign-feature.scss
  assets/scss/03-organisms/_campaign-video.scss
  assets/scss/04-templates/_marketing-campaign.scss
  changelogs/DP-16073.md
  patternlab/backstopjs/reference/regression_page_marketing-campaign-as-solid_0_document_0_phone.png
  patternlab/backstopjs/reference/regression_page_marketing-campaign-as-solid_0_document_1_tablet.png
  patternlab/backstopjs/reference/regression_page_marketing-campaign_0_document_0_phone.png
  patternlab/backstopjs/reference/regression_page_marketing-campaign_0_document_1_tablet.png
  patternlab/backstopjs/reference/regression_template_01-content-types-marketing-campaign_0_document_0_phone.png
  patternlab/backstopjs/reference/regression_template_01-content-types-marketing-campaign_0_document_1_tablet.png
  patternlab/styleguide/source/_patterns/03-organisms/by-template/campaign-video.twig
  patternlab/styleguide/source/_patterns/03-organisms/by-template/key-message.twig
  patternlab/styleguide/source/_patterns/04-templates/01-content-types/marketing-campaign.twig
  patternlab/styleguide/source/_patterns/05-pages/marketing-campaign.json
  patternlab/styleguide/source/_patterns/05-pages/marketing-campaign.twig
  patternlab/styleguide/source/_patterns/05-pages/marketing-campaign~as-solid.json
Labels: external review, internal review

#765 Fix auto add changelog for dependentbot fingerprint
  .circleci/config.yml
  .circleci/dependabot.sh
  changelogs/dependabot.md
  changelogs/hotfix-auto-add-changelog
  react/package-lock.json
  react/package.json
Labels: internal review

#776 Patternlab/DP-16102: Update campaign video styling
  assets/scss/03-organisms/_campaign-video.scss
  changelogs/DP-16102.md
  patternlab/backstopjs/reference/regression_page_marketing-campaign_0_document_0_phone.png
  patternlab/backstopjs/reference/regression_page_marketing-campaign_0_document_1_tablet.png
  patternlab/styleguide/source/_patterns/03-organisms/by-template/campaign-video.md
  patternlab/styleguide/source/_patterns/03-organisms/by-template/campaign-video.twig
  patternlab/styleguide/source/_patterns/05-pages/marketing-campaign.json
Labels: external review, internal review, patternlab

#775 fix decorative display in alert header
  assets/scss/02-molecules/_emergency-header.scss
  changelogs/Dp-16063
  react/backstop/data/bitmaps_reference/vrt_organisms_GeneralTeaser_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/vrt_organisms_GeneralTeaser_0_document_1_tablet.png
  react/backstop/data/bitmaps_reference/vrt_organisms_TableofContents_TableofContents_with_ColoredHeading_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/vrt_organisms_TableofContents_TableofContents_with_ColoredHeading_0_document_1_tablet.png
  react/backstop/data/bitmaps_reference/vrt_organisms_TableofContents_TableofContents_with_SidebarHeading_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/vrt_organisms_TableofContents_TableofContents_with_SidebarHeading_0_document_1_tablet.png
  react/src/components/atoms/links/DecorativeLink/style.scss
Labels: external review, internal review

#783 DP-16028 Fix video transcription link display
  assets/scss/01-atoms/_video.scss
  changelogs/DP-16028.md
Labels: internal review, patternlab

#777 DP-16109: Campaign key message overlay box positioning fix
  changelogs/DP-16109.md
  patternlab/styleguide/source/_patterns/03-organisms/by-template/key-message.twig
Labels: internal review, patternlab

#778 Hotfix/auto changelog formatting
  .circleci/dependabot.sh
  changelogs/dependabot.md
  changelogs/hotfix-auto-changelog-formatting.md
Labels: external review, internal review

#314 DP-10665 [a11y: search.mass.gov] The state seal in the footer
  changelogs/DP-10665.md
  react/backstop/data/bitmaps_reference/vrt_organisms_Footer_Footer_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/vrt_organisms_Footer_Footer_0_document_1_tablet.png
  react/backstop/data/bitmaps_reference/vrt_organisms_Footer_Footer_with_live_JSON_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/vrt_organisms_Footer_Footer_with_live_JSON_0_document_1_tablet.png
  react/src/components/organisms/Footer/Footer.stories.js
  react/src/components/organisms/Footer/index.js
Labels: Ready For Internal Review

#794 react/DP-16106: Fix teaser search bug in GenTeaser
  changelogs/DP-16106.md
  react/src/components/organisms/GenTeaser/TeaserSearch/index.js
Labels: internal review

#796 Sync Develop with Master (Mayflower Release 9.28.0)
  CHANGELOG.md
  changelogs/DP-10665.md
  changelogs/DP-15349.md
  changelogs/DP-15689.md
  changelogs/DP-16028.md
  changelogs/DP-16106.md
  changelogs/DP-16109.md
  changelogs/DP-16115.md
  changelogs/dependabot-gulp-header.md
  changelogs/dependabot-gulp-sass.md
  changelogs/dependabot.md
  changelogs/hotfix-auto-changelog-formatting.md
Labels: internal review

#797 DP-16106: Fix gen teaser bug
  assets/scss/03-organisms/_gen-teaser.scss
  changelogs/DP-16106.md
  react/backstop/data/bitmaps_reference/vrt_organisms_GenTeaser_GenTeaser__as_Laws_and_Regs_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/vrt_organisms_GenTeaser_GenTeaser__as_Laws_and_Regs_0_document_1_tablet.png
  react/backstop/data/bitmaps_reference/vrt_organisms_GenTeaser_GenTeaser_as_DataCatalog_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/vrt_organisms_GenTeaser_GenTeaser_as_DataCatalog_0_document_1_tablet.png
  react/backstop/data/bitmaps_reference/vrt_organisms_GenTeaser_GenTeaser_as_Data_Download_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/vrt_organisms_GenTeaser_GenTeaser_as_Data_Download_0_document_1_tablet.png
  react/backstop/data/bitmaps_reference/vrt_organisms_GenTeaser_GenTeaser_as_Dataset_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/vrt_organisms_GenTeaser_GenTeaser_as_Dataset_0_document_1_tablet.png
  react/backstop/data/bitmaps_reference/vrt_organisms_GenTeaser_GenTeaser_as_Event_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/vrt_organisms_GenTeaser_GenTeaser_as_Event_0_document_1_tablet.png
  react/backstop/data/bitmaps_reference/vrt_organisms_GenTeaser_GenTeaser_as_News_0_document_0_phone.png
  react/backstop/data/bitmaps_reference/vrt_organisms_GenTeaser_GenTeaser_as_News_0_document_1_tablet.png
  react/src/components/organisms/GenTeaser/GenTeaser.stories.js
  react/src/components/organisms/GenTeaser/index.js
  react/src/components/organisms/Header/index.js
Labels: internal review

#800 Mayflower Release 9.28.1
  CHANGELOG.md
  changelogs/DP-16106.md
Labels: internal review

#806 BugFix (React): Icons
  changelogs/react-icon-bugfix.md
  react/src/components/atoms/icons/Icon/assets/data.svg
  react/src/components/atoms/icons/Icon/assets/linkedin.svg
  react/src/components/atoms/icons/Icon/assets/map.svg
  react/src/components/atoms/icons/Icon/assets/questionmark.svg
  react/src/components/atoms/icons/Icon/assets/twitter.svg
Labels: React, internal review

#799 Update h2 font size
  assets/scss/00-base/mixins/_ma-typography.scss
  changelogs/DP-16271
  patternlab/backstopjs/reference/regression_page_binder-page-cover_0_document_1_tablet.png
  patternlab/backstopjs/reference/regression_page_binder-page-internal_0_document_1_tablet.png
  patternlab/backstopjs/reference/regression_page_bio-page_0_document_1_tablet.png
  patternlab/backstopjs/reference/regression_page_board-decision_0_document_1_tablet.png
  patternlab/backstopjs/reference/regression_page_contact-row-examples_0_document_1_tablet.png
  patternlab/backstopjs/reference/regression_page_detail-for-service-howto-location_0_document_1_tablet.png
  patternlab/backstopjs/reference/regression_page_event-end-date-with-time_0_document_1_tablet.png
  patternlab/backstopjs/reference/regression_page_event-end-date_0_document_1_tablet.png
  patternlab/backstopjs/reference/regression_page_event-public-meeting_0_document_1_tablet.png
  patternlab/backstopjs/reference/regression_page_event-recurring_0_document_1_tablet.png
  patternlab/backstopjs/reference/regression_page_event_0_document_1_tablet.png
  patternlab/backstopjs/reference/regression_page_executive-order_0_document_1_tablet.png
  patternlab/backstopjs/reference/regression_page_form-page-example_0_document_1_tablet.png
  patternlab/backstopjs/reference/regression_page_guide-section-all-fields_0_document_1_tablet.png
  patternlab/backstopjs/reference/regression_page_guide_0_document_1_tablet.png
  patternlab/backstopjs/reference/regression_page_information-details-preContent-media_0_document_1_tablet.png
  patternlab/backstopjs/reference/regression_page_information-details-responsive-table_0_document_1_tablet.png
  patternlab/backstopjs/reference/regression_page_information-details-table-of-contents_0_document_1_tablet.png
  patternlab/backstopjs/reference/regression_page_information-details-toc-and-responsive-tables_0_document_1_tablet.png
  patternlab/backstopjs/reference/regression_page_information-details_0_document_1_tablet.png
  patternlab/backstopjs/reference/regression_page_listing-links_0_document_1_tablet.png
  patternlab/backstopjs/reference/regression_page_location-park-content_0_document_1_tablet.png
  patternlab/backstopjs/reference/regression_page_marketing-campaign-as-solid_0_document_1_tablet.png
  patternlab/backstopjs/reference/regression_page_marketing-campaign_0_document_1_tablet.png
  patternlab/backstopjs/reference/regression_page_organization-boards_0_document_1_tablet.png
  patternlab/backstopjs/reference/regression_page_organization-detail_0_document_1_tablet.png
  patternlab/backstopjs/reference/regression_page_organization-elected-official_0_document_1_tablet.png
  patternlab/backstopjs/reference/regression_page_organization-lite-menu-variation_0_document_1_tablet.png
  patternlab/backstopjs/reference/regression_page_organization_0_document_1_tablet.png
  patternlab/backstopjs/reference/regression_page_people-listing_0_document_1_tablet.png
  patternlab/backstopjs/reference/regression_page_policy-advisory-directive_0_document_1_tablet.png
  patternlab/backstopjs/reference/regression_page_press-release-with-image_0_document_1_tablet.png
  patternlab/backstopjs/reference/regression_page_press-release-with-video_0_document_1_tablet.png
  patternlab/backstopjs/reference/regression_page_press-release_0_document_1_tablet.png
  patternlab/backstopjs/reference/regression_page_regulation_0_document_1_tablet.png
  patternlab/backstopjs/reference/regression_page_rules-of-court_0_document_1_tablet.png
  patternlab/backstopjs/reference/regression_page_service-flexible-link-groups_0_document_1_tablet.png
  patternlab/backstopjs/reference/regression_page_service_0_document_1_tablet.png
  patternlab/backstopjs/reference/regression_page_site-alert_0_document_1_tablet.png
  patternlab/backstopjs/reference/regression_page_topic-your-government_0_document_1_tablet.png
  patternlab/backstopjs/reference/regression_page_topic_0_document_1_tablet.png
  patternlab/backstopjs/reference/regression_template_01-content-types-alert_0_document_1_tablet.png
  patternlab/backstopjs/reference/regression_template_01-content-types-binder-page_0_document_1_tablet.png
  patternlab/backstopjs/reference/regression_template_01-content-types-bio_0_document_1_tablet.png
  patternlab/backstopjs/reference/regression_template_01-content-types-court-rules_0_document_1_tablet.png
  patternlab/backstopjs/reference/regression_template_01-content-types-event_0_document_1_tablet.png
  patternlab/backstopjs/reference/regression_template_01-content-types-form-page_0_document_1_tablet.png
  patternlab/backstopjs/reference/regression_template_01-content-types-organization-detail_0_document_1_tablet.png
  patternlab/backstopjs/reference/regression_template_01-content-types-policy-advisory_0_document_1_tablet.png
  patternlab/backstopjs/reference/regression_template_01-content-types-press_0_document_1_tablet.png
  patternlab/backstopjs/reference/regression_template_01-content-types-services-flexible-link-groups_0_document_1_tablet.png
  patternlab/backstopjs/reference/regression_template_01-content-types-services_0_document_1_tablet.png
  patternlab/backstopjs/reference/regression_template_stacked-row-template_0_document_1_tablet.png
  patternlab/backstopjs/reference/regression_template_stacked-rows-with-external-sidebar-template_0_document_1_tablet.png
  react/backstop/data/bitmaps_reference/vrt_organisms_RichText_0_document_1_tablet.png
  react/backstop/data/bitmaps_reference/vrt_organisms_TeaserListing_0_document_1_tablet.png
Labels: internal review

#805 React DP-16257: Extend collapse to pass a min dimension value
  changelogs/DP-16257.md
  react/src/components/animations/Collapse/index.js
Labels: React, internal review

#798 DP-16164 Adjustable key message container height
  assets/scss/03-organisms/_key-message.scss
  changelogs/DP-16164.md
  patternlab/backstopjs/reference/regression_page_marketing-campaign-as-solid_0_document_0_phone.png
  patternlab/backstopjs/reference/regression_page_marketing-campaign-as-solid_0_document_1_tablet.png
Labels: internal review, patternlab

#809 Sync Develop with Master (Release 9.29.0)
  CHANGELOG.md
  changelogs/DP-16164.md
  changelogs/DP-16257.md
  changelogs/DP-16271
  changelogs/react-icon-bugfix.md
Labels: internal review
